taki-kim/Taki-town

- app/globals.css
- app/layout.tsx
- app/page.module.css
- styles/reset.css
- add reset.css
- set page layout
> design: set page layout

- app/globals.css
- app/layout.tsx
- styles/theme.css
- add global style theme file.
> design: add global style theme

- app/globals.css
- app/page.module.css
- components/header/dark-mode/dark-mode-icon.tsx
- components/header/dark-mode/light-mode-icon.tsx
- components/header/header.module.css
- components/header/header.tsx
- components/header/theme-change-button/dark-mode-icon.module.css
- components/header/theme-change-button/dark-mode-icon.tsx
- components/header/theme-change-button/light-mode-icon.module.css
- components/header/theme-change-button/light-mode-icon.tsx
- components/header/theme-change-button/theme-change-button.tsx
- styles/theme.css
- utils/cookies.ts
> feat: add dark-mode & light-mode

- app/page.module.css
- app/page.tsx
- package-lock.json
- package.json
- pages/api/test.ts
- utils/db.ts
- connect mongoDB
- test to fetch data
> Feat : connect db

- app/globals.css
- app/page.module.css
- app/page.tsx
- components/main-page/introduction.module.css
- adjust introduction component's design
> Design: adjust introduction design

- app/globals.css
- app/layout.tsx
- app/page.module.css
- components/footer/footer.module.css
- components/footer/footer.tsx
- components/header/header.tsx
- components/main-logo/main-logo.module.css
- components/main-logo/main-logo.tsx
- package-lock.json
- package.json
> feat: add footer

- app/admin/login/page.module.css
- app/admin/login/page.tsx
- app/admin/page.tsx
- app/globals.css
- app/layout.tsx
- components/footer/footer.module.css
- styles/theme.css
- add admin's login page
- add login page's design layout
> Design: add login page

- app/admin/login/page.tsx
- components/auth-form/auth-form.tsx
- fixed code styles on Login function
> Fix: fixed code styles on Login function

- app/layout.tsx
- components/header/header.tsx
- components/header/logout-button/log-out-button.module.css
- components/header/logout-button/log-out-button.tsx
- providers/next-auth-provider.tsx
- add log-out function
- add session provider on the root page
> Feat: Logout & Session Provider

- app/admin/page.tsx
- app/globals.css
- components/header/logout-button/log-out-button.tsx
- components/page-guard/page-gaurd.module.css
- components/page-guard/page-guard.tsx
- add page-guard
- add auto log-out function
> feat : add page-guard

- app/page.tsx
- app/posts/layout.tsx
- app/posts/page.tsx
- components/posts/header/posts-header.tsx
- components/posts/post-list/post-list.tsx
- pages/api/post/get-all-posts.ts
- utils/postPage.ts
> Feat: Get Post

- app/[postSlug]/page.module.css
- app/[postSlug]/page.tsx
- components/article/header.module.css
- components/article/header.tsx
- components/article/text-container.module.css
- components/article/text-container.tsx
- pages/api/post/[postTitle].ts
- add article page design
- add fetching article data
> feat: add article page design & fetch Article data

- components/admin/admin-post-card/edit-delete-bar/edit-delete-bar.tsx
- pages/api/post/delete/[postTitle].ts
- add deleting post function on Admin page
> feat: add deleting post function

- components/carousel/carousel.tsx
- components/main-page/about-post-section/dev-posts/dev-posts.tsx
- components/main-page/about-post-section/recent-posts/recent-posts.tsx
- type.ts
- utils/date.ts
- utils/sortPosts.ts
- get recent posts & recent dev-posts on landing page
> Feat: get recent posts

- app/admin/create-post/page.module.css
- app/admin/create-post/page.tsx
- app/admin/edit/[postTitle]/page.module.css
- app/admin/edit/[postTitle]/page.tsx
- app/admin/layout.tsx
- components/admin/submit-button/post-create-button.tsx
- components/carousel/carousel.module.css
- components/carousel/carousel.tsx
- add link on Carousel
- add Date when creating post
- add select box input on creating/editing post page
> Feat : chore

- app/layout.tsx
- components/article/text-container.tsx
- components/header/theme-change-button/theme-change-button.tsx
- hooks/useTheme.ts
- providers/context/theme-provider.tsx
- type.ts
- create context on light/dark-theme
- apply theme-context on react-syntax-highlighter
> Feat : create context on light/dark-theme

- app/admin/edit/[postTitle]/page.tsx
- components/main-page/about-post-section/dev-posts/dev-posts.tsx
- providers/context/theme-provider.tsx
- styles/theme.css
- change dark-mode theme color
- fix error on theme-provider component
- delete useless code
> Feat: design dark theme

- app/about/page.module.css
- app/about/page.tsx
- update about page's introduction
> Docs: update my introduction

- app/admin/create-post/page.tsx
> fix: update createPost

- .eslintrc.json
> fix: update lint rule

- components/article-card/article-card.module.css
- components/article/header.module.css
- components/carousel/carousel.module.css
- components/footer/footer.tsx
- components/header/header-list.module.css
- components/header/header.tsx
- components/main-logo/main-logo.module.css
- components/main-page/about-post-section/about-post-section.module.css
- components/main-page/about-post-section/dev-posts/dev-posts.module.css
- components/main-page/about-post-section/recent-posts/recent-posts.module.css
- components/main-page/introduction.module.css
- components/main-page/introduction.tsx
- styles/markdown.css
- update logo design and header's font size
- update markdown css design
- adjust design
> design: update logo design

- app/page.tsx
- app/post/[postSlug]/page.tsx
- app/project/[projectSlug]/page.tsx
- components/article-card/article-card.tsx
- components/carousel/carousel.tsx
- components/header/heade-list.tsx
- components/main-page/about-post-section/dev-posts/dev-posts.tsx
- components/main-page/about-post-section/recent-posts/recent-posts.tsx
- components/posts/header/nav/header-nav.tsx
- components/posts/header/nav/nav-item.tsx
- components/posts/post-list/post-list.tsx
- components/projects/list/project-list.tsx
- type.ts
- utils/article.ts
- utils/header.ts
- update header UX
- update article component's UX
- update CSR to SSR on getting article method
> feat : improve UX

- app/post/[postSlug]/page.tsx
- app/posts/[id]/layout.tsx
- app/posts/page.tsx
- app/project/[projectSlug]/page.tsx
- app/projects/page.tsx
- components/main-page/about-post-section/dev-posts/dev-posts.tsx
- components/main-page/about-post-section/recent-posts/recent-posts.tsx
- components/posts/post-list/post-list.tsx
- components/projects/list/project-list.tsx
- constant.ts
- utils/fetchData.ts
- apply SSR on GET method
- add constant file
> Feat: apply SSR on GET method

- components/main-page/introduction.tsx
> feat: optimize wallpaper image

- app/post/[postSlug]/page.tsx
- components/metadata/metadata.tsx
- components/post-anchor/anchor-card/anchor-card-next.tsx
- components/post-anchor/anchor-card/anchor-card.module.css
- components/post-anchor/anchor-card/anchor-card.tsx
- components/post-anchor/post-anchor.module.css
- components/post-anchor/post-anchor.tsx
- styles/theme.css
- type.ts
- utils/postPage.ts
- add prev & next posts on posting page
> [Feat] post anchor

- components/post-anchor/anchor-card/anchor-card.module.css
- type.ts
- utils/postPage.ts
- adjust post-anchor's design
- fix bug on getting prev/next relevant posts
> [Feat] update post anchor

- app/post/[postSlug]/page.tsx
- components/button/input-button/input-button.module.css
- components/button/input-button/input-button.tsx
- components/comment/comment-container.module.css
- components/comment/comment-container.tsx
- components/comment/comment-input/comment-input.module.css
- components/comment/comment-input/comment-input.tsx
- hooks/useInputs.ts
- pages/api/comment/create/create-comment.ts
- styles/theme.css
- type.ts
- utils/fetchData.ts
- add input-button-component
- add create-comment-api
- add comment-input-component
> [feat] create-comment on post-page

- components/comment/comment-card/comment-card.module.css
- components/comment/comment-card/comment-card.tsx
- components/comment/comment-card/comment-edit-form/comment-edit-form.module.css
- components/comment/comment-card/comment-edit-form/comment-edit-form.tsx
- components/comment/comment-container.tsx
- components/comment/comment-input/comment-input.module.css
- components/comment/comment-input/comment-input.tsx
- components/comment/comments-list/comments-list.module.css
- components/comment/comments-list/comments-list.tsx
- components/comment/recomment-card/recomment-card.module.css
- components/comment/recomment-card/recomment-card.tsx
- pages/api/comment/get/[articleTitle].ts
- type.ts
- utils/date.ts
> Feat: get comments

- components/comment/comment-card/comment-card.module.css
- components/comment/comment-card/comment-card.tsx
- components/comment/comment-card/comment-edit-form/comment-edit-form.module.css
- components/comment/comment-card/comment-edit-form/comment-edit-form.tsx
- components/comment/comment-container.tsx
- components/comment/comments-list/comments-list.module.css
- components/comment/comments-list/comments-list.tsx
- components/comment/recomment-card/recomment-card.module.css
- pages/api/comment/create/create-comment.ts
- pages/api/comment/edit/edit-comment.ts
- type.ts
- utils/fetchData.ts
- apply hashed password & auth system on creating/updating comments
- apply verification cases on comments-component
- update comment-component's design
> Feat : comment auth

- app/admin/page.tsx
- components/admin/admin-comment-card/admin-comment-card.module.css
- components/admin/admin-comment-card/admin-comment-card.tsx
- components/admin/admin-comment-card/recomment-form/admin-recomment-form.module.css
- components/admin/admin-comment-card/recomment-form/admin-recomment-form.tsx
- components/admin/admin-comment-list/admin-comment-list.module.css
- components/admin/admin-comment-list/admin-comment-list.tsx
- components/comment/recomment-card/recomment-card.module.css
- pages/api/comment/get/get-all-comments.ts
- pages/api/recomment/create/[commentId].ts
- utils/fetchData.ts
- add admin's managing-recomment-component
- make it admin to update recomment
> Feat: admin's updating recomment function

- app/layout.tsx
- components/comment/comment-card/comment-edit-form/comment-edit-form.tsx
- components/comment/comment-container.tsx
- components/comment/comment-input/comment-input.tsx
- hooks/useCommentRefetch.ts
- providers/context/comment-refetch-provider.tsx
- utils/fetchData.ts
- able to load new comment list when visitor creates/edits a comment
- add context provider to trigger to refetch comment list
- add custom hook about refetching comment list
> Feat: refetch comment list

- pages/api/auth/[...nextauth].ts
> Fix : fix next-auth error

- app/admin/create-article/page.tsx
- app/admin/edit/post/[postTitle]/page.tsx
- components/article/text-container.tsx
- constant.ts
- package-lock.json
- package.json
- rehypeRaw is react-markdown's plugin to render html tag.
- add rehypeRaw on the posting page, and user can see Youtube video by Iframe tag
> Feat : add rehype raw

- app/globals.css
- components/article-card/article-card.module.css
- components/carousel/carousel.module.css
- components/carousel/carousel.tsx
- components/comment/comment-card/comment-card.module.css
- components/comment/comment-card/comment-card.tsx
- components/comment/recomment-card/recomment-card.module.css
- components/comment/recomment-card/recomment-card.tsx
- components/header/heade-list.tsx
- components/header/header-list.module.css
- components/main-page/posts-nav-section/posts-nav-section.module.css
- components/main-page/posts-nav-section/posts-nav-section.tsx
- components/posts/header/nav/header-nav.module.css
- components/posts/header/nav/nav-item.module.css
- styles/markdown.css
- styles/theme.css
- add font on markdown.css
- add gradient on article-card
- add animation on main-header
- improve UX on carousel
- chore: adjust little stuff on design ui
> Feat: update design 02

- pages/api/openai/getRelatedArticles.ts
- vercel.json
- update ai prompt
- add vercel.json to set fetch duration time
> Feat: fix related article

- components/admin/admin-project-card/admin-project-card.tsx
- fix admin-project-deleting bug
> fix: fix project deleting bug

- components/footer/footer.tsx
> feat: update footer info

- README.md
- components/main-page/about-post-section/about-post-section.module.css
- components/main-page/introduction.module.css
> Docs: update README.md

- components/button/button.module.css
- components/carousel/carousel.module.scss
- components/carousel/carousel.tsx
- components/main-page/about-post-section/dev-posts/dev-posts.module.scss
- components/main-page/about-post-section/recent-posts/recent-posts.module.scss
- components/main-page/posts-nav-section/posts-nav-section.module.scss
- styles/theme.scss
- update button design
- update main-page design
> Feat : update button design

- components/carousel/carousel.module.scss
- components/main-page/posts-nav-section/posts-nav-section.module.scss
- styles/theme.scss
- 메인 페이지 포스트 카테고리 네비게이션 디자인 업데이트
> Design: update main-page design

- components/article-card/article-card.module.css
- components/main-page/highlight-list/highlight-list.module.scss
- components/main-page/introduction/Introduction.module.scss
- components/main-page/introduction/text-auto-slider/TextAutoSlider.module.scss
> design: adjust main-page design

- app/page.module.scss
- components/button/nav-button.tsx
- components/footer/footer.module.css
- components/main-page/highlight-list/FeaturedProjects.tsx
- components/main-page/highlight-list/LatestPost.tsx
- components/main-page/highlight-list/highlight-list.module.scss
- hooks/useFloatingEffect.ts
- styles/theme.scss
- add floatin-effect-hook
- update global-css design
> Feat/floating UI

- components/article-card/ArticleCard.module.scss
- components/article-card/ArticleCard.stories.tsx
- components/article-card/ArticleCard.tsx
- components/main-page/highlight-list/FeaturedProjects.tsx
- components/main-page/highlight-list/LatestPost.tsx
- components/posts/post-list/post-list.tsx
- components/projects/list/project-list.tsx
- add article card story
- rename compoent to camel case
> Feat: add article card story
